[Theme]
backgroundColor=#1a1b26
textColor=#cdd6f4
subtextColor=#a6adc8
accentColor=#7aa2f7
surface0=#313244
surface1=#45475a
surface2=#585b70
mutedColor=#6c7086
errorColor=#f38ba8
font=FiraCode Nerd Font
monoFont=FiraCode Nerd Font Mono
use24HourClock=true
background=assets/background.jpg
