[Theme]
backgroundColor=#1A1B26
textColor=#C0CAF5
subtextColor=#A9B1D6
accentColor=#7AA2F7
surface0=#292E42
surface1=#3B4261
surface2=#414868
mutedColor=#565F89
errorColor=#F7768E
font=CaskaydiaCove Nerd Font
use24HourClock=true
