# General Window & Playback Settings
osc=no
border=no
save-position-on-quit=yes

# Subtitle Autoloading & Preferences
sub-auto=fuzzy
sub-file-paths=sub:subs:subtitles:Subtitles:Sub:Subs
slang=en,eng,enUS,en-US
alang=en,eng,ja,jp,jpn

# Subtitle Appearance & Styling
sub-font='sans-serif'
sub-font-size=40
sub-border-size=2.5
sub-shadow-offset=1
sub-pos=95
