
###################
### MY PROGRAMS ###
###################


# Set programs that you use
$terminal = alacritty
$fileManager = dolphin
$menu = hyprlauncher

exec-once = waybar & hyprpaper

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

source = ./monitors.conf

source = ./decorations.conf

source = ./input.conf

source = ./keybinds.conf

source = ./windowrules.conf
