# Qutebrowser theme — generated from active theme

# Completion menu
c.colors.completion.fg = "{{text}}"
c.colors.completion.odd.bg = "{{crust}}"
c.colors.completion.even.bg = "{{base}}"
c.colors.completion.category.fg = "{{blue}}"
c.colors.completion.category.bg = "{{crust}}"
c.colors.completion.category.border.top = "{{crust}}"
c.colors.completion.category.border.bottom = "{{crust}}"
c.colors.completion.item.selected.fg = "{{text}}"
c.colors.completion.item.selected.bg = "{{surface0}}"
c.colors.completion.item.selected.border.top = "{{surface0}}"
c.colors.completion.item.selected.border.bottom = "{{surface0}}"
c.colors.completion.item.selected.match.fg = "{{peach}}"
c.colors.completion.match.fg = "{{peach}}"
c.colors.completion.scrollbar.fg = "{{surface1}}"
c.colors.completion.scrollbar.bg = "{{crust}}"

# Context menu
c.colors.contextmenu.disabled.bg = "{{crust}}"
c.colors.contextmenu.disabled.fg = "{{overlay1}}"
c.colors.contextmenu.menu.bg = "{{mantle}}"
c.colors.contextmenu.menu.fg = "{{text}}"
c.colors.contextmenu.selected.bg = "{{surface0}}"
c.colors.contextmenu.selected.fg = "{{text}}"

# Downloads
c.colors.downloads.bar.bg = "{{mantle}}"
c.colors.downloads.start.fg = "{{base}}"
c.colors.downloads.start.bg = "{{blue}}"
c.colors.downloads.stop.fg = "{{base}}"
c.colors.downloads.stop.bg = "{{green}}"
c.colors.downloads.error.fg = "{{red}}"

# Hints
c.colors.hints.fg = "{{base}}"
c.colors.hints.bg = "{{yellow}}"
c.colors.hints.match.fg = "{{green}}"

# Keyhint widget
c.colors.keyhint.fg = "{{text}}"
c.colors.keyhint.suffix.fg = "{{yellow}}"
c.colors.keyhint.bg = "{{mantle}}"

# Messages
c.colors.messages.error.fg = "{{red}}"
c.colors.messages.error.bg = "{{base}}"
c.colors.messages.error.border = "{{red}}"
c.colors.messages.warning.fg = "{{yellow}}"
c.colors.messages.warning.bg = "{{base}}"
c.colors.messages.warning.border = "{{yellow}}"
c.colors.messages.info.fg = "{{sapphire}}"
c.colors.messages.info.bg = "{{base}}"
c.colors.messages.info.border = "{{sapphire}}"

# Prompts
c.colors.prompts.fg = "{{text}}"
c.colors.prompts.border = "{{teal}}"
c.colors.prompts.bg = "{{mantle}}"
c.colors.prompts.selected.bg = "{{surface0}}"
c.colors.prompts.selected.fg = "{{text}}"

# Statusbar
c.colors.statusbar.normal.fg = "{{blue}}"
c.colors.statusbar.normal.bg = "{{mantle}}"
c.colors.statusbar.insert.fg = "{{green}}"
c.colors.statusbar.insert.bg = "{{surface0}}"
c.colors.statusbar.passthrough.fg = "{{blue}}"
c.colors.statusbar.passthrough.bg = "{{surface0}}"
c.colors.statusbar.private.fg = "{{mauve}}"
c.colors.statusbar.private.bg = "{{surface0}}"
c.colors.statusbar.command.fg = "{{text}}"
c.colors.statusbar.command.bg = "{{mantle}}"
c.colors.statusbar.command.private.fg = "{{mauve}}"
c.colors.statusbar.command.private.bg = "{{surface0}}"
c.colors.statusbar.caret.fg = "{{mauve}}"
c.colors.statusbar.caret.bg = "{{surface0}}"
c.colors.statusbar.caret.selection.fg = "{{teal}}"
c.colors.statusbar.caret.selection.bg = "{{surface0}}"
c.colors.statusbar.progress.bg = "{{blue}}"
c.colors.statusbar.url.fg = "{{text}}"
c.colors.statusbar.url.error.fg = "{{red}}"
c.colors.statusbar.url.hover.fg = "{{teal}}"
c.colors.statusbar.url.success.http.fg = "{{peach}}"
c.colors.statusbar.url.success.https.fg = "{{green}}"
c.colors.statusbar.url.warn.fg = "{{yellow}}"

# Tabs
c.colors.tabs.bar.bg = "{{crust}}"
c.colors.tabs.indicator.start = "{{blue}}"
c.colors.tabs.indicator.stop = "{{green}}"
c.colors.tabs.indicator.error = "{{red}}"
c.colors.tabs.odd.fg = "{{overlay0}}"
c.colors.tabs.odd.bg = "{{surface0}}"
c.colors.tabs.even.fg = "{{overlay0}}"
c.colors.tabs.even.bg = "{{surface0}}"
c.colors.tabs.pinned.even.bg = "{{surface0}}"
c.colors.tabs.pinned.even.fg = "{{overlay0}}"
c.colors.tabs.pinned.odd.bg = "{{surface0}}"
c.colors.tabs.pinned.odd.fg = "{{overlay0}}"
c.colors.tabs.pinned.selected.even.fg = "{{base}}"
c.colors.tabs.pinned.selected.even.bg = "{{mauve}}"
c.colors.tabs.pinned.selected.odd.fg = "{{base}}"
c.colors.tabs.pinned.selected.odd.bg = "{{mauve}}"
c.colors.tabs.selected.odd.fg = "{{base}}"
c.colors.tabs.selected.odd.bg = "{{mauve}}"
c.colors.tabs.selected.even.fg = "{{base}}"
c.colors.tabs.selected.even.bg = "{{mauve}}"

# Tooltips
c.colors.tooltip.bg = "{{mantle}}"
c.colors.tooltip.fg = "{{text}}"
